# ████████████████████████████████████████
# █ This is the config file for the bot. █
# █ DO NOT SHARE THESE VALUES!           █
# ████████████████████████████████████████

---

# This is also called the API key.
consumer_key:
# This is also called the API secret.
consumer_secret:
access_token:
access_token_secret:
